language: php

dist: trusty

matrix:
  include:
  - php: 7.3
  env: ANALYSIS='true'
# - php: 7.4
    


before_install:
  - sudo apt-get -qq update
  - yes | pecl install imagick
  - sudo apt-get install -y ghostscript
  - travis_retry composer self-update


before_script:
- composer install -n

script:
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpstan analyse src ; fi

after_success:
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/php-coveralls --coverage_clover=clover.xml -v ; fi
