version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - /home/olivier/git/mobilecms-api-slim-74:/var/www/html/mobilecms-api-slim
    
    ports:
      - 8888:80
    restart: unless-stopped

networks:
  internal:
    driver: bridge